spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kafkademo
    username: root
    password: 2020
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: manishmachha@gmail.com
    password: gutb oobj datm osyp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 9090